title: Hello, world! I'm Adrien Morvan
description: > # this means to ignore newlines until "baseurl:"
  Playing with software, algorithms and machine learning
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Adrien Morvan
author-img: adrien.jpg
about-author: I'm a machine learning engineer focused on building data product and solving new challenges with ML.
social-github: admor
social-linkedin: adrien-morvan-
social-email: morvan.adr@gmail.com

# Disqus
discus-identifier: disqus_kERvMsBMAi # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 15
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
